# Generated by Django 5.1.1 on 2024-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja pozarządowa', 'Organizacja pozarządowa'), ('zbiórka lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=50)),
                ('categories', models.ManyToManyField(to='oddam_w_dobre_rece_app.category')),
            ],
        ),
    ]
